/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./mobile.html",
    "./create-invoice-step1.html",
    "./create-invoice-step2.html",
    "./create-invoice-step3.html",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--color-surface-variant)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "secondary": "var(--color-secondary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface": "var(--color-surface)",
        "error": "var(--color-error)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary-fixed": "var(--color-primary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary": "var(--color-tertiary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "error-container": "var(--color-error-container)",
        "surface-container": "var(--color-surface-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary": "var(--color-on-secondary)",
        "on-error": "var(--color-on-error)",
        "primary": "var(--color-primary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-background": "var(--color-on-background)",
        "outline": "var(--color-outline)",
        "tertiary-container": "var(--color-tertiary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        "background": "var(--color-background)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-dim": "var(--color-surface-dim)"
      },
      borderRadius: {
        "DEFAULT": "var(--radius-default)",
        "lg": "var(--radius-lg)",
        "xl": "var(--radius-xl)",
        "full": "var(--radius-full)"
      },
      spacing: {
        "stack-lg": "24px",
        "table-cell-padding": "12px 16px",
        "stack-sm": "8px",
        "container-padding": "32px",
        "stack-xs": "4px",
        "stack-md": "16px",
        "section-gap": "40px",
        "gutter-mobile": "12px",
        "margin-mobile": "16px",
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px"
      },
      fontFamily: {
        "display-invoice": ["Inter", "sans-serif"],
        "headline-section": ["Inter", "sans-serif"],
        "body-tabular": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-invoice": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-section": ["18px", {"lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-tabular": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-main": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "numeric-data": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
